### ISSUE TITLE
README should explain what this library does

### ISSUE THREAD

**Issue by rufuspollock** [zelima/recline-to-vega-spec#2]
README should explain (at least briefly) what this library really does.

README should have a code example of using the library.

If the library will be installed from npm (this one may not be) then instructions should be provided.

**Comment by zelima** [comment]
Please review README improvements https://github.com/zelima/recline-to-vega-spec/commit/c1de3c3749c96d0ce8a0d87e67adc66aa0e10fe2

**Comment by rufuspollock** [comment]
FIXED. @zelima looks good. Well done.
